camunda.bpm.admin-user:
  id: nikhil
  password: bhardwaj
server:
  port: 9192
  
spring:
  name: learn-camunda-service
spring:
  datasource:
    url: jdbc:h2:mem:camunda
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

